# Generated by Django 4.2.2 on 2023-06-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('pnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=120)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
