# Generated by Django 4.2.2 on 2023-07-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0002_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
